common:
  allow_snapshots: False
  audio_fs: 2000
  wsize_sec: 1
  wstep_sec: 2.5
  audio_crop_sec: 2.0
  DEBUG: False

downstream:
  type: binary
  datasets:
    - pascal
    - physionet2016
  epochs: 200
  batch_size: 64
  patience: 20
  lr: 0.0001
  freeze: True
  augment: True
  # class_weights expects 3 ints -> [5, 3, 1] or None
  class_weights:
  tensorboard: False

model_load_asset: False

ssl:
  datasets:
    - 'fpcgdb'
    - 'pascal'
    - 'physionet2016'
  tensorboard: True
  epochs: 50
  batch_size: 128
  patience: 5
  backbone: cnn
  temperature: 0.1
  warmup_scaling: linear
  base_learning_rate: 0.1
  offset: 0.0
  # Leave blank for None
  augmentation1:
    - fliprandom
  augmentation2:
    - flipud
    - cutofffilter_100_50_2000
    - noaugmentation
    - randomscaling


paths:
  ephnogram: /home/vasileios/workspace/Datasets/ephnogram
  fpcgdb: /home/vasileios/workspace/Datasets/fpcgdb
  pascal: /home/vasileios/workspace/Datasets/pascal
  physionet2016: /home/vasileios/workspace/Datasets/physionet2016
  physionet2022: /home/vasileios/workspace/Datasets/physionet2022
  sufhsdb: /home/vasileios/workspace/Datasets/sufhsdb
  tmp_path: /home/vasileios/tmp/pcg-ssl
  results: /home/vasileios/tmp/pgc-ssl/results.csv
